#%RAML 1.0 NamedExample
CreateContactExample:
  displayName: Create Update contact
  value:
    firstName: 'Bob'
    lastName: 'Frederick'
    dob: '06/21/1980'
    gender: 'M'
    title: 'mr'
    email: 'mainn@mule.com'
    phone: '1234567890'
    preferred: 'email'
    addressType: 'home'
    addressNumber: 124
    address: '123 mainn street'
    addressUnit: '1a'
    addressCity: 'edison'
    addressState: 'NJ'
    adressZipcode: 08820
    
    addressType1: 'home'
    addressNumber1: 124
    address1: '123 mainn street'
    addressUnit1: '1a'
    addressCity1: 'edison'
    addressState1: 'NJ'
    adressZipcode1: 08820